cc_library(
    name = "colorsensor",
    srcs = [
        "@__bazelrio_com_revrobotics_frc_colorsensorv3-cpp_linuxathena//:all",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@__bazelrio_com_revrobotics_frc_colorsensorv3-cpp_headers//:headers",
        "@bazelrio//libraries/wpilibc",
    ],
)
