java_import(
    name = "new_commands",
    jars = ["@__bazelrio_edu_wpi_first_wpilibnewcommands_wpilibnewcommands-java//jar:file"],
    visibility = ["//visibility:public"],
    deps = [
        "//libraries/java/wpilib/wpilibj",
    ],
)
