java_import(
    name = "wpilibj",
    jars = ["@__bazelrio_edu_wpi_first_wpilibj_wpilibj-java//jar:file"],
    visibility = ["//visibility:public"],
    deps = [
        "//libraries/java/wpilib/cameraserver",
        "//libraries/java/wpilib/hal",
        "//libraries/java/wpilib/ntcore",
        "//libraries/java/wpilib/wpimath",
        "//libraries/java/wpilib/wpiutil",
    ],
)
