java_import(
    name = "colorsensor",
    jars = ["@__bazelrio_com_revrobotics_frc_colorsensorv3-java//jar:file"],
    visibility = ["//visibility:public"],
    deps = [
        "//libraries/java/wpilib/wpilibj",
    ],
)
