load("@bazelrio//libraries/tools:tool_launchers.bzl", "executable_tool_launcher")

executable_tool_launcher(
    name = "glass",
    base_repo_name = "__bazelrio_edu_wpi_first_tools_glass",
    macos_app = "Glass.app",
)
