local_repository(
    name = "bazelrio",
    path = "../bazelrio",
)

load("@bazelrio//:deps.bzl", "setup_bazelrio_dependencies")

setup_bazelrio_dependencies()
register_toolchains("@bazelrio//toolchains/roborio")

load("@rules_python//python:pip.bzl", "pip_install")

pip_install(
    name = "__bazelrio_deploy_pip_deps",
    requirements = "@bazelrio//deploy:requirements.txt",
#    requirements_lock = "@bazelrio//deploy:requirements-lock.txt",
)

#load("@__bazelrio_deploy_pip_deps//:requirements.bzl", "install_deps")

#install_deps()
