cc_library(
    name = "subsystems",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.hpp"]),
    visibility = ["//visibility:public"],
    deps = [
        "@bazelrio//libraries/wpilib/commands",
        "@bazelrio//libraries/wpilibc",
    ],
)
