cc_library(
    name = "hal",
    srcs = [
        "@__bazelrio_edu_wpi_first_hal_linuxathena//:all",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//libraries/ni-libraries/chipobject",
        "//libraries/ni-libraries/netcomm",
        "//libraries/ni-libraries/runtime",
        "//libraries/ni-libraries/visa",
        "@__bazelrio_edu_wpi_first_hal_headers//:headers",
    ],
)
