cc_library(
    name = "hal",
    srcs = [
        "@__bazelrio_edu_wpi_first_hal_shared//:all",
    ],
    deps = [
        "@__bazelrio_edu_wpi_first_hal_headers//:headers",
        "//libraries/ni-libraries/chipobject",
        "//libraries/ni-libraries/netcomm",
        "//libraries/ni-libraries/runtime",
        "//libraries/ni-libraries/visa",
    ],
    visibility = ["//visibility:public"],
)
