java_import(
    name = "navx",
    jars = ["@__bazelrio_com_kauailabs_navx_frc_navx-frc-java//jar:file"],
    visibility = ["//visibility:public"],
    deps = [
        "//libraries/java/wpilib/wpilibj",
    ],
)
