load("@bazelrio//libraries/tools:tool_launchers.bzl", "java_tool_launcher")

java_tool_launcher(
    name = "smartdashboard",
    base_repo_name = "__bazelrio_edu_wpi_first_tools_smartdashboard",
    main_class = "edu.wpi.first.smartdashboard.SmartDashboard",
)
