local_repository(
    name = "bazelrio",
    path = "../../bazelrio",
)

load("@bazelrio//:deps.bzl", "setup_bazelrio_dependencies")

setup_bazelrio_dependencies()

register_toolchains("@bazelrio//toolchains/roborio")

load("@rules_python//python:pip.bzl", "pip_install")

pip_install(
    name = "__bazelrio_deploy_pip_deps",
    requirements = "@bazelrio//scripts/deploy:requirements.txt",
)

pip_install(
    name = "__bazelrio_wpiformat_pip_deps",
    requirements = "@bazelrio//scripts/wpiformat:requirements.txt",
)
