local_repository(
    name = "bazelrio",
    path = "../../bazelrio",
)

load("@bazelrio//:deps.bzl", "setup_bazelrio_dependencies")

setup_bazelrio_dependencies()

register_toolchains("@bazelrio//toolchains/roborio")

load("@rules_python//python:pip.bzl", "pip_install")

pip_install(
    name = "__bazelrio_deploy_pip_deps",
    requirements = "@bazelrio//scripts/deploy:requirements.txt",
)

pip_install(
    name = "__bazelrio_wpiformat_pip_deps",
    requirements = "@bazelrio//scripts/wpiformat:requirements.txt",
)

# Necessary if you want to run things that need java, like the wpi tools (shuffleboard, pathweaver, etc)
load("@bazelrio//toolchains/jdk:toolchain_config.bzl", "configure_java_toolchain")

configure_java_toolchain()
