cc_library(
    name = "wpilibc",
    srcs = [
        "@__bazelrio_edu_wpi_first_wpilibc_linuxathena//:all",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//libraries/hal",
        "//libraries/ntcore",
        "//libraries/wpimath",
        "//libraries/wpiutil",
        "@__bazelrio_edu_wpi_first_wpilibc_headers//:headers",
    ],
)
