java_import(
    name = "old_commands",
    jars = ["@__bazelrio_edu_wpi_first_wpiliboldcommands_wpiliboldcommands-java//jar:file"],
    visibility = ["//visibility:public"],
    deps = [
        "//libraries/java/wpilib/wpilibj",
    ],
)
