cc_library(
    name = "runtime",
    linkstatic = 1,
    visibility = ["//visibility:public"],
    deps = [
        "@__bazelrio_edu_wpi_first_ni-libraries_runtime_linuxathena//:shared_libs",
    ],
)
