load("@bazelrio//libraries/tools:tool_launchers.bzl", "java_tool_launcher")

java_tool_launcher(
    name = "pathweaver",
    base_repo_name = "__bazelrio_edu_wpi_first_tools_pathweaver",
    main_class = "edu.wpi.first.pathweaver.Main",
)
