java_import(
    name = "wpimath",
    jars = ["@__bazelrio_edu_wpi_first_wpimath_wpimath-java//jar:file"],
    visibility = ["//visibility:public"],
    runtime_deps = [
        "@__bazelrio_maven_deps//:org_ejml_ejml_simple",
    ],
    deps = [
        "//libraries/cpp/wpilib/wpimath:jni",
        "//libraries/java/wpilib/wpiutil",
    ],
)
