java_import(
    name = "sparkmax",
    jars = ["@__bazelrio_com_revrobotics_frc_sparkmax-java//jar:file"],
    visibility = ["//visibility:public"],
    deps = [
        "//libraries/cpp/rev/sparkmax:jni",
        "//libraries/java/wpilib/wpilibj",
    ],
)
