java_import(
    name = "sparkmax",
    jars = ["@__bazelrio_com_revrobotics_frc_sparkmax-java//jar:file"],
    visibility = ["//visibility:public"],
    deps = [
        "@bazelrio//libraries/cpp/rev/sparkmax",
        "@bazelrio//libraries/java/wpilib/wpilibj",
    ],
)
