java_import(
    name = "ntcore",
    jars = ["@__bazelrio_edu_wpi_first_ntcore_ntcore-java//jar:file"],
    visibility = ["//visibility:public"],
    deps = [
        "//libraries/java/wpilib/wpiutil",
        "//libraries/cpp/wpilib/ntcore:jni",
    ],
)
