java_import(
    name = "cscore",
    jars = ["@__bazelrio_edu_wpi_first_cscore_cscore-java//jar:file"],
    visibility = ["//visibility:public"],
    deps = [
        "//libraries/cpp/wpilib/cscore:jni",
        "//libraries/java/wpilib/wpiutil",
    ],
)
