cc_library(
    name = "sparkmax",
    srcs = [
        "@__bazelrio_com_revrobotics_frc_sparkmax-cpp_linuxathena//:all",
        "@__bazelrio_com_revrobotics_frc_sparkmax-driver_linuxathena//:all",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@__bazelrio_com_revrobotics_frc_sparkmax-cpp_headers//:headers",
        "@bazelrio//libraries/wpilibc",
    ],
)
