java_import(
    name = "phoenix",
    jars = [
        "@__bazelrio_com_ctre_phoenix_api-java//jar:file",
        "@__bazelrio_com_ctre_phoenix_wpiapi-java//jar:file",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@bazelrio//libraries/cpp/ctre/phoenix",
        "@bazelrio//libraries/java/wpilib/wpilibj",
    ],
)
