cc_library(
    name = "ntcore",
    srcs = [
        "@__bazelrio_edu_wpi_first_ntcore_shared//:all",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@__bazelrio_edu_wpi_first_ntcore_headers//:headers",
    ],
)
