load("@bazelrio//:defs.bzl", "robot_jvm_binary")

robot_jvm_binary(
    name = "robot",
    main_class = "frc.robot.Main",
    team_number = 1337,
    runtime_deps = [
        "//src/main/java/frc/robot",
    ],
)
