cc_library(
    name = "chipobject",
    linkstatic = 1,
    visibility = ["//visibility:public"],
    deps = [
        "@__bazelrio_edu_wpi_first_ni-libraries_chipobject_linuxathena//:shared_libs",
    ],
)
