cc_library(
    name = "wpiutil",
    srcs = [
        "@__bazelrio_edu_wpi_first_wpiutil_shared//:all",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@__bazelrio_edu_wpi_first_wpiutil_headers//:headers",
    ],
)
