java_import(
    name = "wpinet",
    jars = ["@__bazelrio_edu_wpi_first_wpinet_wpinet-java//jar:file"],
    visibility = ["//visibility:public"],
    deps = [
        "//libraries/cpp/wpilib/wpinet:jni",
        "//libraries/java/wpilib/wpiutil",
    ],
)
