java_library(
    name = "deploy",
    srcs = ["Deploy.java"],
    visibility = ["//visibility:public"],
    deps = [
        "@__bazelrio_maven_deps//:com_hierynomus_sshj",
        "@__bazelrio_maven_deps//:me_tongfei_progressbar",
        "@__bazelrio_maven_deps//:net_sourceforge_argparse4j_argparse4j",
        "@__bazelrio_maven_deps//:org_slf4j_slf4j_nop",
        "@bazel_tools//tools/java/runfiles",
    ],
)
