cc_library(
    name = "commands",
    srcs = [
        "@__bazelrio_edu_wpi_first_wpilibnewcommands_linuxathena//:all",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@__bazelrio_edu_wpi_first_wpilibnewcommands_headers//:headers",
        "@bazelrio//libraries/wpilibc",
    ],
)
