java_import(
    name = "wpiutil",
    jars = ["@__bazelrio_edu_wpi_first_wpiutil_wpiutil-java//jar:file"],
    visibility = ["//visibility:public"],
    deps = [
        "@bazelrio//libraries/cpp/wpilib/wpiutil",
    ],
)
