# TODO update to use aliases when they exist
java_library(
    name = "commands",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/frc/robot/subsystems",
        "@__bazelrio_edu_wpi_first_wpilibj_wpilibj-java//jar",
        "@__bazelrio_edu_wpi_first_wpilibnewcommands_wpilibnewcommands-java//jar",
    ],
)
