cc_library(
    name = "navx",
    srcs = [
        "@__bazelrio_com_kauailabs_navx_frc_navx-cpp_linuxathena//:all",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@__bazelrio_com_kauailabs_navx_frc_navx-cpp_headers//:headers",
        "@bazelrio//libraries/wpilibc",
    ],
)
