# TODO update to use aliases when they exist
java_library(
    name = "subsystems",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@__bazelrio_edu_wpi_first_wpilibj_wpilibj-java//jar",
        "@__bazelrio_edu_wpi_first_wpilibnewcommands_wpilibnewcommands-java//jar",
        "@__bazelrio_edu_wpi_first_wpimath_wpimath-java//jar",
    ],
)
