java_binary(
    name = "robotbuilder",
    main_class = "robotbuilder.RobotBuilder",
    visibility = ["//visibility:public"],
    runtime_deps = ["@__bazelrio_edu_wpi_first_tools_robotbuilder//jar"],
)
