java_import(
    name = "revlib",
    jars = ["@__bazelrio_com_revrobotics_frc_revlib-java//jar:file"],
    visibility = ["//visibility:public"],
    deps = [
        "//libraries/cpp/rev/revlib",
        "//libraries/java/wpilib/wpilibj",
    ],
)
