cc_library(
    name = "navx",
    srcs = ["@__bazelrio_com_kauailabs_navx_frc_navx-frc-cpp_sources//:sources"],
    linkstatic = 1,
    visibility = ["//visibility:public"],
    deps = [
        "//libraries/cpp/wpilib/wpilibc",
        "@__bazelrio_com_kauailabs_navx_frc_navx-frc-cpp_headers//:headers",
    ],
)
