cc_library(
    name = "navx",
    linkstatic = 1,
    visibility = ["//visibility:public"],
    srcs = ["@__bazelrio_com_kauailabs_navx_frc_navx-cpp_sources//:sources"],
    deps = [
        "@__bazelrio_com_kauailabs_navx_frc_navx-cpp_headers//:headers",
        "//libraries/cpp/wpilib/wpilibc",
    ]
)
