java_import(
    name = "cameraserver",
    jars = ["@__bazelrio_edu_wpi_first_cameraserver_cameraserver-java//jar:file"],
    visibility = ["//visibility:public"],
    deps = [
        "//libraries/java/wpilib/cscore",
    ],
)
