java_import(
    name = "wpilibj",
    jars = ["@__bazelrio_edu_wpi_first_wpilibj_java//file"],
    deps = [
        "//libraries/java/cameraserver",
        "//libraries/java/wpimath",
        "//libraries/java/wpiutil",
        "//libraries/java/hal",
    ],
    visibility = ["//visibility:public"],
)
