java_import(
    name = "hal",
    jars = ["@__bazelrio_edu_wpi_first_hal_hal-java//jar:file"],
    visibility = ["//visibility:public"],
    deps = [
        "//libraries/cpp/wpilib/hal:jni",
    ],
)
