cc_library(
    name = "wpimath",
    srcs = [
        "@__bazelrio_edu_wpi_first_wpimath_shared//:all",
    ],
    deps = [
        "@__bazelrio_edu_wpi_first_wpimath_headers//:headers",
        "//libraries/wpiutil",
    ],
    visibility = ["//visibility:public"],
)
