cc_library(
    name = "wpimath",
    srcs = [
        "@__bazelrio_edu_wpi_first_wpimath_shared//:all",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//libraries/wpiutil",
        "@__bazelrio_edu_wpi_first_wpimath_headers//:headers",
    ],
)
