load("@bazelrio//libraries/tools:tool_launchers.bzl", "java_tool_launcher")

java_tool_launcher(
    name = "shuffleboard",
    base_repo_name = "__bazelrio_edu_wpi_first_tools_shuffleboard",
    main_class = "edu.wpi.first.shuffleboard.app.Main",
)
