name: Lint and Format

on: [pull_request, push]

jobs:
  wpiformat:
    name: "buildifier"
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
        id: go

      - uses: actions/checkout@v2

      - name: Install Buildifier
        run: |
          cd $(mktemp -d)
          GO111MODULE=on go get github.com/bazelbuild/buildtools/buildifier@4.0.1

      - name: Run buildifier
        run: buildifier --lint=fix -r .

      - name: Check Output
        run: git --no-pager diff --exit-code HEAD

      - name: Generate diff
        run: git diff HEAD > buildifier-fixes.patch
        if: ${{ failure() }}

      - uses: actions/upload-artifact@v2
        with:
          name: buildifier fixes
          path: buildifier-fixes.patch
        if: ${{ failure() }}
