name: Update README
on:
  push:
    tags:
    - '*'
jobs:
    update-readme:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                ref: main
            - run: |
                TAG=${GITHUB_REF#refs/*/} SHA256=$(curl -sSL https://github.com/bazelRio/bazelRio/archive/refs/tags/$TAG.zip | sha256sum | cut -d' ' -f1) envsubst < README.md.template > README.md
            - name: Set title name
              run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v3
              with:
                base: main
                title: Update README for tag ${{ env.RELEASE_VERSION }}
